### ISSUE TITLE
Female Mosquito output from MBITES is a little weird

### ISSUE THREAD

**Issue by dtcitron** [smitdave/MASH-Main#126]
Sample output:

<{
  "id": [12],
  "tile": [1],
  "time": [2, 2, 2],
  "sites": [8, 4, 4],
  "search": [true, false, false],
  "behavior": ["B", "B", "D"],
  "bloodHosts": [0],
  "timeFeed": [0],
  "siteFeed": [0],
  "probeAndFeed": [false]
}>

Mosquitoes appear to be stuck in the "B" mode.

Also, the outputs that should come with <trackProbe_Mosquito_Female()> don't appear in the log anymore.

Unsure if this is two problems or just one.

**Comment by slwu89** [comment]
might have been fixed, see this line (line 103) https://github.com/smitdave/MASH-Main/commit/6369ef96fe62b6105815509af721baf8f48efb9b#diff-5a597898f9ac7ee28344765098293aabL103

issue was possibly that `mbites_pPPRFlight` in MBITES-BloodMeal.R was being used as P(death), changed to 1-P(death) = P(survive), seems more reasonable now.

**Comment by dtcitron** [comment]
Still broken

{
  "id": [31],
  "tile": [1],
  "time": [6, 7, 8, 9, 10, 11, 12, 12, 12],
  "sites": [5, 11, 11, 12, 12, 17, 2, 2, 2],
  "search": [true, false, true, false, true, true, false, true, true],
  "behavior": ["B", "B", "B", "B", "B", "B", "B", "B", "D"],
  "bloodHosts": [0],
  "timeFeed": [0],
  "siteFeed": [0],
  "probeAndFeed": [false]
}

**Comment by slwu89** [comment]
Did you rebuild the package? I ran it a few times and couldn't replicate the previous odd behavior.
